name: flutter_clean_architecture_template
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  auto_route: ^7.2.0
  cupertino_icons: ^1.0.2
  dio: ^5.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.18.6
  flutter_localization: ^0.1.11
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  injectable: ^2.1.1
  intl: ^0.18.0
  json_annotation: ^4.8.1
  meta: ^1.9.1
  retrofit: ^4.0.1

dev_dependencies:
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.4
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  injectable_generator: ^2.1.5
  json_serializable: ^6.7.0
  retrofit_generator: ^7.0.1

flutter:
  uses-material-design: true
